### ISSUE TITLE
Conditional Style Marked as Inline

### ISSUE THREAD

**Issue by degroote22** [Intellicode/eslint-plugin-react-native#81]
Currently I'm getting flagged for this.

```
<div
  style={{
    ...styles.mainContainer,
    left: (left === 0) ? 0 : container.left, // eslint-disable-line react-native/no-inline-styles
  }}
>
```

Is this really some anti-pattern?
Thanks for your time.

**Comment by Intellicode** [comment]
Hi, sorry for the late response, I guess it depends on the team if you decide its an anti-pattern. Of course there are cases where you can't get around this, but it would also be possible to define a style specifically for that case and only assign it if left === 0, instead of just the property. It is completely up to you :)
